//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, I&apos;m Renaud, a Windows Development MVP from Belgium. I built this tool to help developers get their apps in the store easily. If you want to get in touch, contact me on : .
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started !.
        /// </summary>
        public static string Call1 {
            get {
                return ResourceManager.GetString("Call1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Call2 {
            get {
                return ResourceManager.GetString("Call2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Call3 {
            get {
                return ResourceManager.GetString("Call3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome. Here we are....
        /// </summary>
        public static string Modal1a {
            get {
                return ResourceManager.GetString("Modal1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, tell us about yourself !.
        /// </summary>
        public static string Modal1b {
            get {
                return ResourceManager.GetString("Modal1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your developer name ?.
        /// </summary>
        public static string Modal1c {
            get {
                return ResourceManager.GetString("Modal1c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As it appears in the store....
        /// </summary>
        public static string Modal1d {
            get {
                return ResourceManager.GetString("Modal1d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any email address where users can contact you ?.
        /// </summary>
        public static string Modal1e {
            get {
                return ResourceManager.GetString("Modal1e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        public static string Modal2a {
            get {
                return ResourceManager.GetString("Modal2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, we would like to hear about your awesome app !.
        /// </summary>
        public static string Modal2b {
            get {
                return ResourceManager.GetString("Modal2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it have a name ?.
        /// </summary>
        public static string Modal2c {
            get {
                return ResourceManager.GetString("Modal2c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uses your internet connection to download and update the content. This application doesn’t:.
        /// </summary>
        public static string PrivacyAnswer1 {
            get {
                return ResourceManager.GetString("PrivacyAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any question about this application, please send an email to .
        /// </summary>
        public static string PrivacyAnswer2 {
            get {
                return ResourceManager.GetString("PrivacyAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect &amp; use any personal information.
        /// </summary>
        public static string PrivacyBullet1a {
            get {
                return ResourceManager.GetString("PrivacyBullet1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store any personal data.
        /// </summary>
        public static string PrivacyBullet1b {
            get {
                return ResourceManager.GetString("PrivacyBullet1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share it to third party.
        /// </summary>
        public static string PrivacyBullet1c {
            get {
                return ResourceManager.GetString("PrivacyBullet1c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Does this application collect or use your personal information?.
        /// </summary>
        public static string PrivacyQuestion1 {
            get {
                return ResourceManager.GetString("PrivacyQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Contact..
        /// </summary>
        public static string PrivacyQuestion2 {
            get {
                return ResourceManager.GetString("PrivacyQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy for.
        /// </summary>
        public static string PrivacyTitle {
            get {
                return ResourceManager.GetString("PrivacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 8 Privacy.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your last privacy page !.
        /// </summary>
        public static string Welcome1 {
            get {
                return ResourceManager.GetString("Welcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure you&apos;re fed up with setting up all those privacy things....
        /// </summary>
        public static string Welcome2 {
            get {
                return ResourceManager.GetString("Welcome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you&apos;re just 3-click away from getting your very own hosted privacy page on .
        /// </summary>
        public static string Welcome3 {
            get {
                return ResourceManager.GetString("Welcome3", resourceCulture);
            }
        }
    }
}
